version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - shop_smart
    restart: always
    volumes:
      - ./logs:/usr/src/app/logs

  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${API_DB_ROOT_PASS}
      MYSQL_DATABASE: ${API_DB_NAME}
      MYSQL_USER: ${API_DB_USER}
      MYSQL_PASSWORD: ${API_DB_PASS}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --authentication-policy=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/custom.cnf 
    ports:
      - "${API_DB_PORT}:3306"
    networks:
      - shop_smart
    restart: always

  redis:
    image: redis:7.2.4
    networks:
      - shop_smart
    restart: always

  backup:
    image: alpine:3.19
    depends_on:
      - db
    volumes:
      - /opt/shop_smart/backups:/backups
      - ./scripts:/scripts
    environment:
      MYSQL_DATABASE: ${API_DB_NAME}
      MYSQL_USER: ${API_DB_USER}
      MYSQL_PASSWORD: ${API_DB_PASS}
      MYSQL_HOST: ${API_DB_HOST}
      MYSQL_PORT: ${API_DB_PORT}
      TZ: America/Sao_Paulo
    networks:
      - shop_smart
    mem_limit: 256M
    cpus: 0.5
    command: >
      sh -c "
        apk add --no-cache mysql-client tzdata &&
        chmod +x /scripts/*.sh &&
        if [ -n \"$$MANUAL\" ]; then
          /scripts/manual_backup_db.sh \"$$@\"
        else
          /scripts/backup_db.sh
        fi
      "

networks:
  shop_smart:

volumes:
  db_data:
